<section class="h-screen w-screen flex justify-center items-center flex-col">
    <form action="/login" method="post" class="capitalize text-slate-600 flex justify-center items-center flex-col">
        <label for="icon" class="bg-gradient-to-tl from-cyan-500 to-green-600 via-green-600 bg-clip-text text-transparent">
            <i class="fa fa-fire text-9xl"></i>
        </label>
        <label for="email" class="mt-2">
            <p><i class="fa fa-envelope-open"></i> email</p>
            <input type="email" name="email" id="email" placeholder="email" class="border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="password" class="mt-2">
            <p><i class="fa fa-lock"></i> password</p>
            <input type="password" name="password" id="password" placeholder="password" class="border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="submit" class="w-full my-4">
            <input type="submit" value="Login" name="submit" id="name" class="w-full p-2 rounded-sm shadow-md cursor-pointer text-white bg-gradient-to-r from-cyan-500 to-green-600 ">
        </label>
        <?php
        if (isset($message)) {
        ?>
            <p class="text-red-500 font-medium bg-green-200 w-full p-3 rounded-sm text-center">
                <?php
                echo $message;
                ?>
            </p>
        <?php
        }
        ?>
    </form>
</section>